### 상품 재고 조회.
GET http://localhost:8080/product/api/stock/v1/40164991
Content-Type: application/json

### 상품 재고 차감.
PATCH http://localhost:8080/product/api/stock/v1/40164991/stock
Content-Type: application/json

{
  "quantity": 15
}
